name: Sourcemod CI

on:
  push:
    branches: [ "sourcemod" ]
  pull_request:
    branches: [ "sourcemod" ]

  workflow_dispatch:

env:
  REPO_NAME: "${{ github.event.repository.name }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Warden
        uses: actions/checkout@v3
#       - name: Checkout multicolors
#         uses: actions/checkout@v3
#         with:
#           repository: Bara/Multi-Colors
#           path: multicolors
      - name: Checkout hosties
        uses: actions/checkout@v3
        with:
          repository: notfoundname/sm-hosties-plus
          path: hosties
      - name: Compile Warden
        uses: SheplyRam/compile-sourcepawn-plugin@v1
        with:
          input: scripting/warden.sp
          output: plugins/warden.smx
          includes: "scripting/include hosties/scripting/include"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "${{ env.REPO_NAME }}-${{ env.BUILD_NUMBER }}"
          path: |
            ./
            !.git
            !.github
            !.gitignore
            !./sourcescramble
            !./hosties
            !Warden.code-workspace

